### ISSUE TITLE
supported=0, detected=0

### ISSUE THREAD

**Issue by Yikeun** [ivmech/ivport-v2#8]
I want to use two cameras.

I came to the i2cdetect step.

but 
~$ vcgencmd get_camera
supported=0 detected=0
The output is as above.

What should I do?

I want to use CAM1 and CAM3. How do I connect the jumpers?

**Comment by ivmech** [comment]
you should "enable camera" from raspi-config

**Comment by Yikeun** [comment]
@ivmech Thank you for quick reply.
[http://postfiles8.naver.net/MjAxNzA4MjJfNzkg/MDAxNTAzNDA3Njc5Mzk4.BApo0alJRo9bU2hs52bNy0z3Cn18BXdyZDQyLqroqzMg.N3LWhNtQsPYeD-zLN7ak12pZSnHO3I4k4Tr-mtPuUrcg.PNG.zagumhyang/ivmech.png?type=w2](url)

Why does this error occur?

**Comment by mar97co** [comment]
Hi everyone, it’s been a long time, but for a university course project, I dug out an IVPORT-V2 QUAD that I’d never used and had been keeping in a drawer. 
I tried everything and **_I found a solution_** that works with a **Raspberry Pi** 4 running [**2023-05-03-raspios-bullseye-armhf.img.xz**](https://downloads.raspberrypi.com/raspios_armhf/images/raspios_armhf-2023-05-03/2023-05-03-raspios-bullseye-armhf.img.xz), **IVPORT-V2 QUAD** and **Raspberry Pi Camera V2.1**.

I followed the steps as described in the README, but I kept getting this error:
```
python3 test_ivport_quad.py
mmal: Cannot read camera info, keeping the defaults for OV5647
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is installed correctly

mmal: Cannot read camera info, keeping the defaults for OV5647
mmal: mmal_vc_component_create: failed to create component 'vc.ril.camera' (1:ENOMEM)
mmal: mmal_component_create_core: could not create component 'vc.ril.camera' (1)
mmal: Failed to create camera component
mmal: main: Failed to create camera component
mmal: Camera is not detected. Please check carefully the camera module is installed correctly
```
Basically, when the Raspberry Pi boots up, it tries to initialize the connected camera, but because the multiplexer is in the way, it can’t find it.
**Ho semplicemente fatto questo:**
1. Disconnected the power from the Raspberry Pi.
2. Connected the camera directly to the Raspberry Pi.
3. Plugged it back in and waited for the boot process to complete.
4. While it was running, I abruptly disconnected the camera and connected it to the IVPORT. Then I connected the IVPORT to the Raspberry Pi.
5. I ran the commands `python3 init_ivport.py` and then `python3 test_ivport_quad.py`
6. Et voilà! The images captured by both cameras had appeared in the folder!

Unfortunately, you'll have to repeat the process after rebooting...

I hope this is still helpful to someone! Bye! :)
